front:
  restart: always
  build: images/nginx
  ports:
    - "80:80"
    - "9000:9000"
  links:
    - "selenium"
  #   - "gearman"
  volumes:
    - /var/www:/var/www
  # extra_hosts:
  #   - "phpstack_mysql_1:192.168.0.164"

# gearman:
#   restart: always
#   build: images/gearman
#   ports:
#     - "4730:4730"
#   volumes:
#     - /var/www:/var/www

selenium:
  restart: always
  build: images/selenium
  ports:
    - "4444:4444"
    - "5900:5900"
